### PR TITLE
Refactor breadcrumbs

### PR DESCRIPTION
**Pull request by yookoala**
**Refactor**
## Description
adapt the new `$page` global for breadcrumb.

## Motivation and Context
See GibbonEdu/core#696

## How Has This Been Tested?
* Locally

### CODE REVIEW

**Review by SKuipers — CHANGES_REQUESTED** [review]
Thanks Koala! Overall looks great, however perhaps a typo in your find-replace: the `$breadcrumb->add` calls should read `$page->breadcrumbs->add`

**Comment by yookoala** [comment]
You're right. Will fix those.

**Comment by yookoala** [comment]
Should have fixed them in d8e58f6. Please check.

**Review by SKuipers — APPROVED** [review]
Looks great, thanks! I'm going to merge & test it out 👍

**Pull request merged**
